project:
  type: website
  output-dir: docs

website:
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: CV.qmd
        text: CV
      - href: Research.qmd
        text: Research
      - href: Teaching.qmd
        text: Teaching
      - href: Industry.qmd
        text: Industry



      

format:
  html:
    theme:
      light: lumen
      dark: solar
    css: styles.css
    toc: true

editor: visual

