project:
  type: website
  output-dir: docs

website:
  title: "KajariaS.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - CV.qmd

      

format:
  html:
    theme:
      dark: solar
      light: minty
    css: styles.css
    toc: true

editor: visual

