---
title: "Research"
---

#### **WORK IN PROGRESS:**

-   *Nature’s Shield: Deciphering Mangroves’ Influence on Property Value Dynamics in the Wake of Hurricane Irma* - (with Susana Ferreira and Yukiko Hashida)
-   *Let ‘Em Grow: Do Florida Coastal Property Owners Value Mangroves?* - (with Susana Ferreira and Yukiko Hashida)
-   *Shoreline Wonders: Navigating Mangroves with Geographic information system*

#### **CONFERENCES & PRESENTATIONS:**

#### **2024:**

-   *Nature’s Shield: Deciphering Mangroves’ Influence on Property Value Dynamics in the Wake of Hurricane Irma* presented at Southern Agricultural Economics Association (SAEA) Annual Meeting, Atlanta, GA, February 3-6, 2024. 
-   *Nature’s Shield: Deciphering Mangroves’ Influence on Property Value Dynamics in the Wake of Hurricane Irma* presented at Association of Environmental and Resource Economists (AERE) Annual Summer Conference, Washington, D.C., May 29 - 31, 2024.

#### **2023:**

-   *Let ‘Em Grow: Do Florida Coastal Property Owners Value Mangroves?* presented at Southern Economic Association (SEA) Annual Meeting, New Orleans, LA, November 18-20, 2023. 
-   *Let ‘Em Grow: Do Florida Coastal Property Owners Value Mangroves?* presented at Agricultural & Applied Economics Association (AAEA) Annual Meeting, Washington, D.C., July 23-25, 2023. 
-   *Let ‘Em Grow: Do Florida Coastal Property Owners Value Mangroves?* presented at Georgia Water Resources Conference (GWRC), Athens, GA, March 30-31, 2023. 
-   *Shoreline Wonders: Navigating Mangroves with Geographic information system* at GIS Day Conference, UGA, Athens, GA, November 15, 2023.
